version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: curriculos-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: curriculos-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # OpenAI
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # MongoDB
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_DATABASE: curriculos_db
      MONGODB_COLLECTION: logs
      MONGODB_USER: admin
      MONGODB_PASSWORD: admin123
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - easyocr_models:/root/.EasyOCR
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongodb_data:
    driver: local
  easyocr_models:
    driver: local
